change print to retunr
fernandezpablo85/python_init pull request #2
Opened 2020-04-27 21:00 UTC by taniavill

2020-04-27 22:02 UTC, seppo0010 commented
usá mensajes de commit más descriptivos que "updated", y en presente, por ejemplo "enable tests, accept varargs for sum"

2020-04-28 19:13 UTC, fernandezpablo85 requested changes

2020-04-28 19:13 UTC, fernandezpablo85 commented on numbers/number.py
> +    return(a+b)
no hacen falta los paréntesis acá 
```suggestion
    return a + b

```

2020-04-28 19:13 UTC, fernandezpablo85 commented on numbers/number.py
> +    return(n%2 == 0)
Lo mismo acá

```suggestion
    return n % 2 == 0

```

2020-04-28 19:13 UTC, fernandezpablo85 commented on numbers/number.py
> +    return(n%2 != 0)
```suggestion
    return n % 2 != 0

```

2020-04-28 19:13 UTC, fernandezpablo85 commented on numbers/number.py
> +    add_all = 0
a `add_all` la llamaría `total`

2020-04-28 19:13 UTC, fernandezpablo85 commented on numbers/number.py
> +    if type(arr[0]) == list:
la forma correcta de preguntar por un tipo en python es 

`if isinstance(arr[0], list)`

2020-04-28 19:13 UTC, fernandezpablo85 commented on numbers/number.py
> +            add_all += numb
si bien anda, no es bueno mezclar indentación. si usabas 4 espacios antes no uses 8 acá

2020-04-28 20:19 UTC, seppo0010 requested changes

2020-04-28 20:19 UTC, seppo0010 commented on numbers/number_test.py
> +#@pytest.mark.skip()
es mejor borrar las líneas en vez de comentarlas :)

2020-04-28 21:17 UTC, taniavill commented on numbers/number.py
> +            add_all += numb
@fernandezpablo85 no encontré otra solución. Alguna pista?

2020-04-29 12:39 UTC, seppo0010 commented
Me parece que lo del triangulo tendría que ir en otro PR ya.

2020-04-29 13:22 UTC, taniavill commented
oka, cierro este entonces y lo subo a otro?


El mié., 29 abr. 2020 a las 9:40, Sebastian Waisbrot (<
notifications@github.com>) escribió:

> Me parece que lo del triangulo tendría que ir en otro PR ya.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/fernandezpablo85/python_init/pull/2#issuecomment-621177067>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/APKAKVKS7FDWPMH6SBS3HCLRPAN2TANCNFSM4MSII4FQ>
> .
>

2020-04-29 21:42 UTC, closed without merging