Triangle.py
fernandezpablo85/python_init pull request #3
Opened 2020-04-29 21:45 UTC by taniavill

Hay dos funciones creadas que dibujan un triángulo, ninguna pasa los test, necesito ayuda!

2020-04-30 00:20 UTC, fernandezpablo85 requested changes

2020-04-30 00:20 UTC, fernandezpablo85 commented on triangles/triangle_h_test.py
>      t = triangle.draw(n=n)
tani, fijate que aca `t = triangle.draw`, o sea, se espera que la función `draw` devuelva el triángulo, que es lo que el test prueba.

vos creo que lo estás armando bien pero en vez de devolverlo (como un string con el triángulo) lo estás imprimiendo con `print` por eso no funciona

2020-05-05 11:27 UTC, seppo0010 requested changes

2020-05-05 11:27 UTC, seppo0010 commented on triangles/triangle.py
> +    #return '\n'.join(triangulo)
por qué print y no return? :cry:

2020-05-05 11:27 UTC, seppo0010 commented on triangles/triangle.py
> +        linea.append('*')
`linea = ['*'] * x`

(en lo posible usá identificadores en inglés también)

2020-05-05 12:56 UTC, taniavill commented on triangles/triangle.py
> +    #return '\n'.join(triangulo)
Seppo, no me funciona con el return, me devuelve  '* \n* * \n* * * \n* * * * \n* * * * * '
Claro está que no pasa las pruebas, pablo me había sugerido usar el join para dibujar el triángulo, esta fue la única forma que encontré, si tenés alguna pista de como solucionarlo, o que puedo googlear, genial!

2020-05-05 15:55 UTC, taniavill commented on triangles/triangle.py
> +    #return '\n'.join(triangulo)
return print('\n'.join(triangulo)) si dibuja el triángulo pero tampoco pasa el test :/

2020-05-05 18:19 UTC, fernandezpablo85 approved these changes

2020-05-05 18:19 UTC, fernandezpablo85 commented on triangles/triangle.py
> +    return ' '.join(new_line)
excelente Tani, te comparto como lo hice yo, muy parecido:

```python
def _line(n):
    stars = ["*" for _ in range(n)]
    return " ".join(stars)


def draw(n):
    lines = [_line(i + 1) for i in range(n)]
    return "\n".join(lines)
```

Algunos detalles:

- uso de [list comprehensions](https://realpython.com/list-comprehension-python/)
- usar `_line` en vez de `line` como nombre, para indicar que es una función accesoria de triángulo y que no está pensada para "el público general" (lo que en otros lenguajes de programación se consideraría "privada")

2020-05-05 18:47 UTC, taniavill commented on triangles/triangle.py
> +    return ' '.join(new_line)
me re había olvidado de las lisas d comprensión y de las funciones privadas

Gracias!

2020-05-05 18:48 UTC, closed without merging